from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path


@dataclass(frozen=True)
class TargetRule:
    label: str
    source: str
    runtime_template: str
    output: str
    manifest: str



def load_rules(config_file: Path) -> list[TargetRule]:
    data = json.loads(config_file.read_text(encoding="utf-8"))
    items = data.get("targets", [])

    rules: list[TargetRule] = []
    for item in items:
        rules.append(
            TargetRule(
                label=item["label"],
                source=item["source"],
                runtime_template=item["runtime_template"],
                output=item["output"],
                manifest=item["manifest"],
            )
        )
    return rules



def _provenance_banner(rule: TargetRule, unit) -> str:
    method_head = ", ".join(unit.method_names[:8])
    if len(unit.method_names) > 8:
        method_head += ", ..."

    lines = [
        "# Generated by tt translate (source-driven emission)",
        f"# Label: {rule.label}",
        f"# Source file: {unit.source_path}",
        f"# Source digest (sha256): {unit.digest}",
        f"# Source class: {unit.class_name} extends {unit.base_name}",
        f"# Source method count: {len(unit.method_names)}",
        f"# Source methods: {method_head}",
        "",
    ]
    return "\n".join(lines)



def render_runtime_text(rule: TargetRule, unit, runtime_text: str) -> str:
    header = _provenance_banner(rule, unit)
    body = runtime_text.replace("\"__CALC_TYPE__\"", json.dumps(unit.calc_kind))
    return header + body



def write_output_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")



def write_manifest(path: Path, rule: TargetRule, unit) -> None:
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "label": rule.label,
        "source": {
            "path": unit.source_path,
            "digest": unit.digest,
            "class_name": unit.class_name,
            "base_name": unit.base_name,
            "method_names": unit.method_names,
            "import_paths": unit.import_paths,
            "calc_kind": unit.calc_kind,
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
