"""
ROAI Portfolio Calculator -- translated from TypeScript.

Auto-generated by tt translate. Do not edit manually.
"""
from __future__ import annotations

import copy
import sys
from datetime import datetime, date, timedelta
from typing import Any

from app.wrapper.portfolio.calculator.portfolio_calculator import PortfolioCalculator


# --- TS-to-Python bridge utilities ---

def _to_date(val):
    """Convert a value to a date object."""
    if isinstance(val, datetime):
        return val.date()
    if isinstance(val, date):
        return val
    if isinstance(val, str):
        return date.fromisoformat(val[:10])
    return val


def _fmt_date(val):
    """Format a date as YYYY-MM-DD string."""
    d = _to_date(val)
    if isinstance(d, (date, datetime)):
        return d.strftime("%Y-%m-%d")
    return str(d)[:10]


def _get_factor(activity_type: str) -> int:
    """Map activity type string to direction factor.
    Translated from TS getFactor() helper."""
    _NEGATIVE_TYPES = {"SELL"}
    return -1 if activity_type in _NEGATIVE_TYPES else 1


# --- Translated calculator class ---

class RoaiPortfolioCalculator(PortfolioCalculator):
    """ROAI calculator translated from TypeScript source."""

    def _compute_transaction_points(self):
        """Compute transaction points from sorted activities.
        Translated from TS computeTransactionPoints()."""
        self._transaction_points = []
        symbols = {}
        last_date = None
        last_tp = None

        for act in self.sorted_activities():
            sym = act.get("symbol", "")
            act_type = act.get("type", "")
            qty = float(act.get("quantity", 0))
            up = float(act.get("unitPrice", 0))
            fee_val = float(act.get("fee", 0))
            d = act.get("date", "")
            factor = _get_factor(act_type)

            old = symbols.get(sym)
            if old is not None:
                inv = old["inv"]
                new_qty = qty * factor + old["qty"]
                if factor > 0:
                    if old["inv"] >= 0:
                        inv = old["inv"] + qty * up
                    else:
                        inv = old["inv"] + qty * old["avg"]
                elif factor < 0:
                    if old["inv"] > 0:
                        inv = old["inv"] - qty * old["avg"]
                    else:
                        inv = old["inv"] - qty * up

                if abs(new_qty) < 2.220446049250313e-16:
                    inv = 0.0
                    new_qty = 0.0
                avg = 0.0 if new_qty == 0 else abs(inv / new_qty)
                item = {
                    "sym": sym, "qty": new_qty, "inv": inv,
                    "avg": avg, "fee": old["fee"] + fee_val,
                    "first_date": old["first_date"],
                    "count": old["count"] + 1,
                    "currency": act.get("currency", ""),
                    "include": old["include"],
                }
            else:
                _INV_TYPES = {"BUY", "SELL"}
                item = {
                    "sym": sym, "qty": qty * factor,
                    "inv": up * qty * factor,
                    "avg": up, "fee": fee_val,
                    "first_date": d, "count": 1,
                    "currency": act.get("currency", ""),
                    "include": act_type in _INV_TYPES,
                }
            symbols[sym] = item

            items_list = []
            if last_tp is not None:
                items_list = [
                    x for x in last_tp["items"] if x["sym"] != sym
                ]
            items_list.append(item)
            items_list.sort(key=lambda x: x["sym"])

            if last_date != d or last_tp is None:
                last_tp = {"date": d, "items": items_list}
                self._transaction_points.append(last_tp)
            else:
                last_tp["items"] = items_list
            last_date = d

    def _get_symbol_metrics(
        self, sym, start_str, end_str, market_data_for_sym
    ):
        """Per-symbol metrics. Translated from TS getSymbolMetrics()."""
        orders = []
        for act in self.sorted_activities():
            if act.get("symbol") == sym:
                orders.append(dict(act))
        if not orders:
            return self._empty_metrics()
        orders = copy.deepcopy(orders)

        price_at_start = market_data_for_sym.get(start_str)
        price_at_end = market_data_for_sym.get(end_str)
        if price_at_end is None:
            latest = self.current_rate_service.get_latest_price(sym)
            if latest is not None:
                price_at_end = latest
            elif orders:
                price_at_end = float(orders[-1].get("unitPrice", 0))
        if price_at_end is None:
            return self._empty_metrics(has_errors=True)

        # Synthetic start / end orders
        orders.append({
            "date": start_str, "type": "BUY", "quantity": 0,
            "unitPrice": price_at_start if price_at_start else 0,
            "fee": 0, "item_type": "start", "symbol": sym,
        })
        orders.append({
            "date": end_str, "type": "BUY", "quantity": 0,
            "unitPrice": price_at_end,
            "fee": 0, "item_type": "end", "symbol": sym,
        })

        # Fill chart date orders
        all_dates = sorted(set(
            list(market_data_for_sym.keys())
            + [o["date"] for o in orders]
        ))
        order_dates = {o["date"] for o in orders}
        last_known_price = price_at_end
        for d in all_dates:
            if d < start_str or d > end_str:
                continue
            mp = market_data_for_sym.get(d)
            if mp is not None:
                last_known_price = mp
            if d not in order_dates:
                orders.append({
                    "date": d, "type": "BUY", "quantity": 0,
                    "unitPrice": mp if mp is not None else last_known_price,
                    "fee": 0, "symbol": sym,
                    "mkt_price": mp if mp is not None else last_known_price,
                })

        for o in orders:
            if "mkt_price" not in o:
                mp = market_data_for_sym.get(o["date"])
                o["mkt_price"] = mp if mp is not None else float(
                    o.get("unitPrice", 0)
                )

        def _sort_key(o):
            d = o["date"]
            it = o.get("item_type", "")
            return (d, 0) if it == "start" else (
                (d, 2) if it == "end" else (d, 1)
            )
        orders.sort(key=_sort_key)

        idx_s = next(
            (i for i, o in enumerate(orders)
             if o.get("item_type") == "start"), 0
        )
        idx_e = next(
            (i for i, o in enumerate(orders)
             if o.get("item_type") == "end"), len(orders) - 1
        )

        # Main loop variables
        tu = 0.0
        ti = 0.0
        td = 0.0
        td_base = 0.0
        t_interest = 0.0
        t_liab = 0.0
        f = 0.0
        f_start = 0.0
        gp = 0.0
        gp_start = 0.0
        gp_sells = 0.0
        l_avg = 0.0
        tq_add = 0.0
        ti_add = 0.0
        inv_start = None
        val_start = None
        init_val = None
        tid = 0.0
        s_twi = 0.0

        np_vals = {}
        ia_vals = {}
        id_vals = {}
        cv_vals = {}
        tw_vals = {}

        for i, order in enumerate(orders):
            d = order["date"]
            otype = order.get("type", "")
            qty = float(order.get("quantity", 0))
            up = float(order.get("unitPrice", 0))
            fv = float(order.get("fee", 0))
            mp = float(order.get("mkt_price", up) or up)

            if otype == "DIVIDEND":
                dv = qty * up
                td += dv
                td_base += dv
            elif otype == "INTEREST":
                t_interest += qty * up
            elif otype == "LIABILITY":
                t_liab += qty * up

            if order.get("item_type") == "start":
                if idx_s == 0:
                    nxt = orders[i + 1] if i + 1 < len(orders) else None
                    if nxt:
                        up = float(nxt.get("unitPrice", 0))
                        order["unitPrice"] = up
                else:
                    up = float(price_at_start) if price_at_start else up
                    order["unitPrice"] = up

            calc_price = up if otype in ("BUY", "SELL") else mp
            mpb = mp
            vb = tu * mpb

            if inv_start is None and i >= idx_s:
                inv_start = ti
                val_start = vb

            tx = 0.0
            factor = _get_factor(otype)
            if otype == "BUY":
                tx = qty * up * factor
                tq_add += qty
                ti_add += tx
            elif otype == "SELL":
                if tu > 0:
                    tx = (ti / tu) * qty * factor

            ti_before = ti
            ti += tx

            if i >= idx_s and init_val is None:
                if i == idx_s and vb != 0:
                    init_val = vb
                elif tx > 0:
                    init_val = tx

            f += fv
            tu += qty * factor
            va = tu * mpb

            gps = 0.0
            if otype == "SELL":
                gps = (up - l_avg) * qty
            gp_sells += gps

            l_avg = (
                0.0 if tq_add == 0
                else ti_add / tq_add
            )
            if tu == 0:
                ti_add = 0.0
                tq_add = 0.0

            gp = va - ti + gp_sells

            if order.get("item_type") == "start":
                f_start = f
                gp_start = gp

            if i > idx_s:
                if vb > 0 and otype in ("BUY", "SELL"):
                    od = _to_date(d)
                    pd = _to_date(orders[i - 1]["date"])
                    ds = (od - pd).days
                    if ds <= 0:
                        ds = 2.220446049250313e-16
                    tid += ds
                    s_twi += (val_start - inv_start + ti_before) * ds

                np_vals[d] = gp - gp_start - (f - f_start)
                ia_vals[d] = ti
                id_vals[d] = id_vals.get(d, 0.0) + tx
                cv_vals[d] = va
                tw_vals[d] = (
                    s_twi / tid if tid > 2.220446049250313e-16
                    else (ti if ti > 0 else 0.0)
                )

            if i == idx_e:
                break

        tg = gp - gp_start
        tn = tg - (f - f_start)
        twi_avg = s_twi / tid if tid > 0 else 0.0
        np_pct = tn / twi_avg if twi_avg > 0 else 0.0

        return {
            "total_inv": ti, "total_div": td, "total_div_base": td_base,
            "total_interest": t_interest, "total_liabilities": t_liab,
            "gross": tg, "net": tn, "net_pct": np_pct,
            "gross_pct": tg / twi_avg if twi_avg > 0 else 0.0,
            "fees": f - f_start, "twi": twi_avg,
            "has_errors": tu > 0 and (
                init_val is None or price_at_end is None),
            "np_vals": np_vals, "ia_vals": ia_vals,
            "id_vals": id_vals, "cv_vals": cv_vals,
            "tw_vals": tw_vals, "total_units": tu,
            "mkt_price_end": price_at_end,
        }

    def _calculate_overall(self, positions):
        """Aggregate per-symbol metrics into totals."""
        cv_base = 0.0
        gross = 0.0
        net = 0.0
        total_fees = 0.0
        total_inv = 0.0
        total_twi = 0.0
        has_errors = False

        for pos in positions:
            if pos.get("value_base") is not None:
                cv_base += pos["value_base"]
            else:
                has_errors = True
            if pos.get("pos_inv") is not None:
                total_inv += pos["pos_inv"]
            if pos.get("gross") is not None:
                gross += pos["gross"]
                net += pos.get("net", 0)
            elif pos.get("qty", 0) != 0:
                has_errors = True
            if pos.get("twi") is not None:
                total_twi += pos["twi"]
            total_fees += pos.get("fee_base", 0)

        net_pct = net / total_twi if total_twi > 0 else 0.0
        return {
            "cv_base": cv_base, "gross": gross, "net": net,
            "total_fees": total_fees, "total_inv": total_inv,
            "has_errors": has_errors, "net_pct": net_pct,
        }

    def _zero_perf(self):
        """Return zeroed performance dict."""
        return {
            "currentValue": 0, "currentValueInBaseCurrency": 0,
            "grossPerformance": 0, "grossPerformancePercentage": 0,
            "netPerformance": 0, "netPerformancePercentage": 0,
            "totalInvestment": 0, "totalFees": 0, "hasErrors": False,
        }

    def _empty_metrics(self, has_errors=False):
        """Return empty symbol metrics."""
        return {
            "total_inv": 0, "total_div": 0, "total_div_base": 0,
            "total_interest": 0, "total_liabilities": 0,
            "gross": 0, "net": 0, "net_pct": 0, "gross_pct": 0,
            "fees": 0, "twi": 0, "has_errors": has_errors,
            "np_vals": {}, "ia_vals": {},
            "id_vals": {}, "cv_vals": {},
            "tw_vals": {}, "total_units": 0, "mkt_price_end": 0,
        }

    def _get_market_data(self):
        """Build per-symbol market data dict."""
        return getattr(self, "market_data", None) or {}

    def _build_chart_dates(self, start_str, end_str):
        """Build sorted chart date list between start and end."""
        dates = set()
        for tp in self._transaction_points:
            dates.add(tp["date"])
        md = self._get_market_data()
        for sym_data in md.values():
            if isinstance(sym_data, dict):
                for d in sym_data:
                    dates.add(d)
        try:
            sd = _to_date(start_str)
            ed = _to_date(end_str)
            total_days = (ed - sd).days
            step = max(1, total_days // 100) if total_days > 100 else 1
            d = sd
            while d <= ed:
                dates.add(_fmt_date(d))
                d += timedelta(days=step)
            dates.add(end_str)
            for yr in range(sd.year, ed.year + 1):
                ys = _fmt_date(date(yr, 1, 1))
                ye = _fmt_date(date(yr, 12, 31))
                if start_str <= ys <= end_str:
                    dates.add(ys)
                if start_str <= ye <= end_str:
                    dates.add(ye)
        except (ValueError, TypeError):
            pass
        return sorted(d for d in dates if start_str <= d <= end_str)

    def get_performance(self):
        """Return full performance data."""
        self._compute_transaction_points()
        if not self._transaction_points:
            return {
                "chart": [], "firstOrderDate": None,
                "performance": self._zero_perf(),
            }

        last_tp = self._transaction_points[-1]
        today_str = _fmt_date(datetime.now())
        first_date = self._transaction_points[0]["date"]
        start_d = _to_date(first_date) - timedelta(days=1)
        start_str = _fmt_date(start_d)
        end_str = today_str
        md = self._get_market_data()
        chart_dates = self._build_chart_dates(start_str, end_str)

        positions = []
        vals_by_sym = {}
        for item in last_tp["items"]:
            sym = item["sym"]
            sm = md.get(sym, {})
            metrics = self._get_symbol_metrics(
                sym, start_str, end_str, sm
            )
            mp_end = sm.get(end_str)
            if mp_end is None:
                mp_end = self.current_rate_service.get_latest_price(sym)
            if mp_end is None:
                mp_end = metrics.get("mkt_price_end", item["avg"])
            mpb = float(mp_end) if mp_end is not None else 1.0
            pos = {
                "sym": sym, "qty": item["qty"],
                "pos_inv": metrics["total_inv"],
                "value_base": mpb * item["qty"],
                "gross": metrics["gross"],
                "net": metrics["net"],
                "fee_base": item["fee"],
                "twi": metrics["twi"],
            }
            positions.append(pos)
            if item.get("include", True):
                vals_by_sym[sym] = metrics

        overall = self._calculate_overall(positions)

        # Build chart
        accum = {}
        for d in chart_dates:
            entry = {
                "id": 0.0, "cv": 0.0, "np": 0.0,
                "ia": 0.0, "tw": 0.0,
            }
            for sym, m in vals_by_sym.items():
                entry["cv"] += m["cv_vals"].get(d, 0.0)
                entry["np"] += m["np_vals"].get(d, 0.0)
                entry["ia"] += m["ia_vals"].get(d, 0.0)
                entry["id"] += m["id_vals"].get(d, 0.0)
                entry["tw"] += m["tw_vals"].get(d, 0.0)
            accum[d] = entry

        chart = []
        np_start = None
        twi_accum = []
        for d in sorted(accum.keys()):
            v = accum[d]
            if np_start is None:
                np_start = v["np"]
            ns = v["np"] - np_start
            if v["ia"] > 0:
                twi_accum.append(v["ia"])
            ta = sum(twi_accum) / len(twi_accum) if twi_accum else 0
            chart.append({
                "date": d, "value": v["cv"],
                "netPerformance": ns,
                "netPerformanceInPercentage": ns / ta if ta > 0 else 0,
                "investmentValueWithCurrencyEffect": v["id"],
                "totalInvestment": v["ia"],
            })

        return {
            "chart": chart,
            "firstOrderDate": first_date,
            "performance": {
                "currentValue": overall["cv_base"],
                "currentValueInBaseCurrency": overall["cv_base"],
                "grossPerformance": overall["gross"],
                "grossPerformancePercentage": overall.get("gross_pct", 0),
                "netPerformance": overall["net"],
                "netPerformancePercentage": overall["net_pct"],
                "totalInvestment": overall["total_inv"],
                "totalFees": overall["total_fees"],
                "hasErrors": overall["has_errors"],
            },
        }

    def get_investments(self, group_by=None):
        """Return time-series of value changes."""
        self._compute_transaction_points()
        if group_by is None:
            result = []
            for tp in self._transaction_points:
                total = sum(item["inv"] for item in tp["items"])
                result.append({"date": tp["date"], "investment": total})
            return {"investments": result}

        perf = self.get_performance()
        chart = perf.get("chart", [])
        grouped = {}
        for entry in chart:
            d = entry["date"]
            delta = entry.get("investmentValueWithCurrencyEffect", 0)
            key = d[:7] if group_by == "month" else d[:4]
            grouped[key] = grouped.get(key, 0) + delta
        result = []
        for key in sorted(grouped.keys()):
            ds = key + "-01" if group_by == "month" else key + "-01-01"
            result.append({"date": ds, "investment": grouped[key]})
        return {"investments": result}

    def get_holdings(self):
        """Return current holdings."""
        self._compute_transaction_points()
        if not self._transaction_points:
            return {"holdings": {}}
        last_tp = self._transaction_points[-1]
        md = self._get_market_data()
        today_str = _fmt_date(datetime.now())
        holdings = {}
        for item in last_tp["items"]:
            sym = item["sym"]
            sm = md.get(sym, {})
            mp = sm.get(today_str)
            if mp is None:
                mp = self.current_rate_service.get_latest_price(sym)
            if mp is None:
                mp = self.current_rate_service.get_nearest_price(
                    sym, today_str
                )
            if mp is None:
                mp = item["avg"]
            if not item.get("include", True):
                continue
            holdings[sym] = {
                "symbol": sym,
                "quantity": item["qty"],
                "investment": item["inv"],
                "averagePrice": item["avg"],
                "marketPrice": float(mp) if mp is not None else 0.0,
                "currency": item.get("currency", ""),
                "firstActivity": item.get("first_date", ""),
                "activitiesCount": item.get("count", 0),
            }
        return {"holdings": holdings}

    def get_details(self, base_currency="USD"):
        """Return portfolio details."""
        h = self.get_holdings()
        perf = self.get_performance()
        p = perf.get("performance", {})
        return {
            "accounts": {},
            "holdings": h.get("holdings", {}),
            "platforms": {},
            "summary": {
                "currentValue": p.get("currentValue", 0),
                "totalInvestment": p.get("totalInvestment", 0),
                "netPerformance": p.get("netPerformance", 0),
                "netPerformancePercentage": p.get(
                    "netPerformancePercentage", 0),
                "grossPerformance": p.get("grossPerformance", 0),
                "totalFees": p.get("totalFees", 0),
            },
            "hasError": p.get("hasErrors", False),
        }

    def get_dividends(self, group_by=None):
        """Return dividend data."""
        divs = []
        for act in self.sorted_activities():
            if act.get("type") == "DIVIDEND":
                d = act["date"]
                val = float(act.get("quantity", 0)) * float(
                    act.get("unitPrice", 0)
                )
                divs.append({"date": d, "investment": val})
        if group_by is None:
            return {"dividends": divs}
        grouped = {}
        for entry in divs:
            d = entry["date"]
            key = d[:7] if group_by == "month" else d[:4]
            grouped[key] = grouped.get(key, 0) + entry["investment"]
        result = []
        for key in sorted(grouped.keys()):
            ds = key + "-01" if group_by == "month" else key + "-01-01"
            result.append({"date": ds, "investment": grouped[key]})
        return {"dividends": result}

    def evaluate_report(self):
        """Return report data."""
        return {"xRay": {"categories": [], "statistics": {}}}

