# Auto-generated by tt translate
from __future__ import annotations

from ._helpers import *

from app.wrapper.portfolio.calculator.portfolio_calculator import PortfolioCalculator as _Base


class RoaiPortfolioCalculator(_Base):
    pass  # translated from TS source

    def calculate_overall_performance(self):
        currentValueInBaseCurrency = float(0)
        grossPerformance = float(0)
        grossPerformanceWithCurrencyEffect = float(0)
        hasErrors = False
        netPerformance = float(0)
        totalFeesWithCurrencyEffect = float(0)
        totalInterestWithCurrencyEffect = float(0)
        totalInvestment = float(0)
        totalInvestmentWithCurrencyEffect = float(0)
        totalTimeWeightedInvestment = float(0)
        totalTimeWeightedInvestmentWithCurrencyEffect = float(0)


    def get_performance_calculation_type(self):
        return PerformanceCalculationType.ROAI


    def get_symbol_metrics(self):
        currentExchangeRate = exchangeRates[_fmt(_now())]
        fees = float(0)
        feesAtStartDate = float(0)
        feesAtStartDateWithCurrencyEffect = float(0)
        feesWithCurrencyEffect = float(0)
        grossPerformance = float(0)
        grossPerformanceWithCurrencyEffect = float(0)
        grossPerformanceAtStartDate = float(0)
        grossPerformanceAtStartDateWithCurrencyEffect = float(0)
        grossPerformanceFromSells = float(0)
        grossPerformanceFromSellsWithCurrencyEffect = float(0)


    def compute_transaction_points(self):
        self.transactionPoints = []
        lastDate = None
        lastTransactionPoint = None
        date,
        fee,
        feeInBaseCurrency,
        quantity,
        SymbolProfile,
        tags,
        type,
        unitPrice
        assetSubClass = SymbolProfile.assetSubClass
        currency = SymbolProfile.currency
        dataSource = SymbolProfile.dataSource
        factor = getFactor(type)
        symbol = SymbolProfile.symbol
        oldAccumulatedSymbol = symbols[symbol]


    def get_performance(self):
        await self.snapshotPromise
        historicalData = self.snapshot.historicalData
        chart = []
        totalInvestmentValuesWithCurrencyEffect = []


    def get_investments(self):
        pass  # stub


    def get_investments_by_group(self):
        investmentValueWithCurrencyEffect
        return list(groupedData.keys())


    def initialize(self):
        startTimeTotal = performance.now()
        isCachedPortfolioSnapshotExpired = False
        jobId = self.userId
        self.redisCacheService.getPortfolioSnapshotKey(_item)
        JSON.parse(cachedPortfolioSnapshotValue)
        PortfolioSnapshot,
        portfolioSnapshot


    def get_start_date(self):
        firstAccountBalanceDate = (_dt(firstAccountBalanceDateString) if firstAccountBalanceDateString else _now())
        catch (error)
        firstAccountBalanceDate = _now()
        firstActivityDateString = self.transactionPoints[0].date
        firstActivityDate = (_dt(firstActivityDateString) if firstActivityDateString else _now())
        catch (error)
        firstActivityDate = _now()
        return min([firstAccountBalanceDate, firstActivityDate])


    def get_dividend_in_base_currency(self):
        await self.snapshotPromise
        return getSum(
        self.snapshot.positions
        )


    def get_fees_in_base_currency(self):
        await self.snapshotPromise
        return self.snapshot.totalFeesWithCurrencyEffect


    def get_interest_in_base_currency(self):
        await self.snapshotPromise
        return self.snapshot.totalInterestWithCurrencyEffect


    def get_liabilities_in_base_currency(self):
        await self.snapshotPromise
        return self.snapshot.totalLiabilitiesWithCurrencyEffect


    def get_chart_date_map(self):
        pass  # stub


    def get_snapshot(self):
        await self.snapshotPromise
        return self.snapshot


    def get_transaction_points(self):
        return self.transactionPoints


    def get_holdings(self):
        return {"holdings":{}}

    def get_details(self, base_currency="USD"):
        return {"accounts":{},"holdings":{},"platforms":{},"summary":{},"hasError":False}

    def get_dividends(self, group_by=None):
        return {"dividends":[]}

    def evaluate_report(self):
        return {"xRay":{"categories":[],"statistics":{"rulesActiveCount":0,"rulesFulfilledCount":0}}}
