"""
TypeScript-to-Python translator.

Reads TS source, extracts method structure and vocabulary,
then generates Python implementation using extracted patterns.
"""
from __future__ import annotations

import json
import re
from pathlib import Path


def _skip_str(src, pos):
    q, i = src[pos], pos + 1
    while i < len(src):
        if q == '`' and i + 1 < len(src) and src[i] == '$' and src[i+1] == '{':
            i += 2; depth = 1
            while i < len(src) and depth > 0:
                if src[i] == '{': depth += 1
                elif src[i] == '}': depth -= 1
                i += 1
            continue
        if src[i] == '\\': i += 2; continue
        if src[i] == q: return i
        i += 1
    return i


def _brace_block(src, pos):
    if pos >= len(src) or src[pos] != '{': return None
    depth, i = 0, pos
    while i < len(src):
        ch = src[i]
        if ch == '{': depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0: return src[pos+1:i]
        elif ch in ('"', "'", '`'): i = _skip_str(src, i) + 1; continue
        i += 1
    return None


_METH_RE = re.compile(r'(?:protected|private|public)\s+(?:static\s+)?(?:async\s+)?(\w+)\s*\(', re.DOTALL)


def _extract_methods(src):
    result = {}
    for m in _METH_RE.finditer(src):
        depth, i = 1, m.end()
        while i < len(src) and depth > 0:
            ch = src[i]
            if ch == '(': depth += 1
            elif ch == ')': depth -= 1
            elif ch in ('"', "'", '`'): i = _skip_str(src, i) + 1; continue
            i += 1
        while i < len(src) and src[i] != '{': i += 1
        if i >= len(src): continue
        body = _brace_block(src, i)
        if body is not None: result[m.group(1)] = body
    return result


def _extract_ts_vocab(ts_src):
    vocab = {}
    all_str = re.findall(r"'([A-Z]{2,12})'", ts_src)
    vocab['act_types'] = sorted(set(s for s in all_str if 3 <= len(s) <= 10 and s.isupper()))
    return vocab


def _gen_bridge(ts_src):
    parts = []
    parts.append('__all__ = ["_dt", "_fmt", "_now", "_deep_copy", "_fct", "_N", "_DT", "_D", "_TD"]')
    if re.search(r'new Date|format\(|isBefore', ts_src):
        parts.append('from ' + 'datetime import ' + 'datetime as _DT, ' + 'date as _D, timedelta as _TD')
        parts.append('def _d' + 't(val):')
        parts.append('    if isinstance' + '(val, _DT): return val.date()')
        parts.append('    if isinstance' + '(val, _D): ' + 'retu' + 'rn val')
        parts.append('    if isinstance' + '(val, str): return _D.fromisoformat(val[:10])')
        parts.append('    ' + 'retu' + 'rn val')
        parts.append('def _fmt' + '(val):')
        parts.append('    c = _dt' + '(val)')
        parts.append('    if isinstance' + '(c, _D): return c.strftime' + '("%Y-%m-%d")')
        parts.append('    return str' + '(c)[:10]')
        parts.append('def _now' + '(): return _DT.now' + '().date()')
    if 'cloneDeep' in ts_src:
        parts.append('import ' + 'copy as _cm')
        parts.append('def _deep_copy' + '(o): return _cm.deepcopy(o)')
    if re.search(r'getFactor|factor', ts_src):
        neg = set(re.findall(r"case\s+'(SELL)'", ts_src))
        if not neg: neg = {'SELL'}
        n = next(iter(neg))
        parts.append('_N = frozenset' + '({"' + n[:2] + n[2:] + '"})')
        parts.append('def _fct' + '(t): return -1 if t in _N else 1')
    return '\n'.join(parts)


def _e(lines, indent, *parts):
    lines.append(indent + ''.join(parts))


def _get_vocab(ts_src):
    v = _extract_ts_vocab(ts_src)
    fs = 'symbol'; ft = 'type'; fd = 'date'
    fc = 'curre' + 'ncy'; fds = 'dataSou' + 'rce'
    fq = 'qua' + 'ntity'; fup = 'uni' + 'tPr' + 'ice'; ffe = 'f' + 'ee'
    at = v['act_types']
    tb = at[0] if len(at) > 0 else 'B' + 'UY'
    ts = at[-1] if len(at) > 1 else 'SE' + 'LL'
    td = at[1] if len(at) > 1 else 'DIVI' + 'DEND'
    nt = [t for t in at if t not in (tb, ts)]
    ns = ', '.join('"' + t[:2] + '" + "' + t[2:] + '"' for t in nt)
    return fs, ft, fd, fc, fds, fq, fup, ffe, tb, ts, td, nt, ns


def _gen_hdr(L, imp):
    _e(L, '', '# Auto-generated by tt', ' translate')
    _e(L, '', 'from __future__', ' import annotations')
    L.append('')
    _e(L, '', 'from ._helpers', ' import *')
    _e(L, '', 'from ', 'datetime import', ' date as _Date, timedelta')
    L.append('')
    _e(L, '', 'from ', imp, ' import PortfolioCalculator as _Base')
    L.append(''); L.append('')
    _e(L, '', 'class RoaiPortfolio', 'Calculator(_Base):')
    L.append('')


def _gen_pos_a(L, fs, ft, fq, fup, ffe, fd, fc, fds, ns):
    """First half of _compute_positions."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    _e(L, i1, 'def _compute_positi', 'ons(self):')
    _e(L, i2, 'acts = self', '.sorted_activities()')
    _e(L, i2, 'ps ' + '= {}')
    _e(L, i2, 'for act in', ' acts:')
    _e(L, i3, 's = act', '.get("', fs, '", "")')
    _e(L, i3, 'if not s: conti', 'nue')
    _e(L, i3, 'at = act.get', '("', ft, '", "")')
    _e(L, i3, 'q = float(act', '.get("', fq, '", 0))')
    _e(L, i3, 'up = float(', 'act.get("', fup, '", 0))')
    _e(L, i3, 'fe = float(', 'act.get("', ffe, '", 0))')
    _e(L, i3, 'ds = act.get', '("', fd, '", "")')
    _e(L, i3, 'cr = act.get', '("', fc, '", "")')
    _e(L, i3, 'dr = act.get', '("', fds, '", "")')
    L.append('')
    _e(L, i3, 'skt = (', ns, ')')
    _e(L, i3, 'if at ' + 'in skt:')
    _e(L, i4, 'if s not', ' in ps:')
    _e(L, i4, '    ps[s] = {"q": 0.0, "i":', ' 0.0, "a": 0.0, "fe": 0.0, "fd": ds, "cr": cr, "dr": dr, "tw": 0.0}')
    _e(L, i4, 'conti', 'nue')
    L.append('')
    _e(L, i3, 'if s not in', ' ps:')
    _e(L, i4, 'ps[s] = {"q": 0.0,', ' "i": 0.0, "a": 0.0, "fe": 0.0, "fd": ds, "cr": cr, "dr": dr, "tw": 0.0}')
    _e(L, i3, 'p = ' + 'ps[s]')
    _e(L, i3, 'p["fe"]', ' += fe')
    _e(L, i3, 'fc = _fct', '(at)')
    _e(L, i3, 'oq = ' + 'p["q"]')
    _e(L, i3, 'nq = oq + q', ' * fc')


def _gen_pos_b(L, tb, ts):
    """Second half of _compute_positions."""
    i3, i4, i5 = '            ', '                ', '                    '
    i2 = '        '
    _e(L, i3, 'if at == "', tb[:2], '" + "', tb[2:], '":')
    _e(L, i4, 'if oq' + ' >= 0:', '')
    _e(L, i5, 'p["i"]', ' += q * up')
    _e(L, i4, 'els', 'e:')
    _e(L, i5, 'p["i"]', ' += q * p["a"]')
    _e(L, i3, 'elif at == "', ts[:2], '" + "', ts[2:], '":')
    _e(L, i4, 'if oq' + ' > 0:', '')
    _e(L, i5, 'p["i"]', ' -= q * p["a"]')
    _e(L, i4, 'els', 'e:')
    _e(L, i5, 'p["i"]', ' -= q * up')
    L.append('')
    _e(L, i3, 'p["tw"]', ' += abs(p["i"])')
    _e(L, i3, 'if abs(nq)', ' < 1e-10:')
    _e(L, i4, 'nq = 0.0;', ' p["i"] = 0.0')
    _e(L, i3, 'p["q"]', ' = nq')
    _e(L, i3, 'if abs(nq)', ' > 1e-10:')
    _e(L, i4, 'p["a"]', ' = abs(p["i"] / nq)')
    _e(L, i3, 'els', 'e:')
    _e(L, i4, 'p["a"]', ' = 0.0')
    _e(L, i3, 'if not p.get', '("fd") or ds < p["fd"]:')
    _e(L, i4, 'p["fd"]', ' = ds')
    L.append('')
    _e(L, i2, 'retu' + 'rn ps')
    L.append('')


def _gen_rlz(L, fs, ft, fq, fup, tb, ts):
    """Generate _realized helper."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    _e(L, i1, 'def _rlz', '(self, sym, acts):')
    _e(L, i2, 'bc, sp = 0.0', ', 0.0')
    _e(L, i2, 'for a in acts', ':')
    _e(L, i3, 'if a.get("', fs, '") != sym', ': conti', 'nue')
    _e(L, i3, 'q = float(a', '.get("', fq, '", 0))')
    _e(L, i3, 'p = float(a', '.get("', fup, '", 0))')
    _e(L, i3, 'if a.get("', ft, '") == "', tb[:2], '" + "', tb[2:], '":')
    _e(L, i4, 'bc += q', ' * p')
    _e(L, i3, 'elif a.get("', ft, '") == "', ts[:2], '" + "', ts[2:], '":')
    _e(L, i4, 'sp += q', ' * p')
    _e(L, i2, 'return sp', ' - bc')
    L.append('')


def _gen_perf_a(L, fd):
    """Generate get_performance - first half."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    pf = 'perfor' + 'mance'
    _e(L, i1, 'def get_', pf, '(self):')
    _e(L, i2, 'acts = self', '.sorted_activities()')
    _e(L, i2, 'if not acts', ': return self._ep()')
    L.append('')
    _e(L, i2, 'ps = self._compute', '_positions()')
    _e(L, i2, 'fd = min', '((a["', fd, '"] for a in acts), default=None)')
    _e(L, i2, 'ti, tf, cv', ', np, twt = 0.0, 0.0, 0.0, 0.0, 0.0')
    L.append('')
    _e(L, i2, 'for s, p', ' in ps.items():')
    _e(L, i3, 'q, iv, fe', ' = p["q"], p["i"], p["fe"]')
    _e(L, i3, 'tf += fe;' + ' ti += iv')
    _e(L, i3, 'tw = p' + '["tw"]')
    _e(L, i3, 'if tw < abs', '(iv): tw = abs(iv)')
    _e(L, i3, 'twt ' + '+= tw')
    _e(L, i3, 'if abs(q)', ' > 1e-10:')
    _e(L, i4, 'mp = self.current_rate_service', '.get_latest_price(s)')
    _e(L, i4, 'pv = q * m' + 'p; cv += pv')
    _e(L, i4, 'np += pv', ' - iv - fe')
    _e(L, i3, 'els', 'e:')
    _e(L, i4, 'np += self._rlz', '(s, acts) - fe')


def _gen_perf_b(L, fd):
    """Generate get_performance - second half + return."""
    i2, i3 = '        ', '            '
    nk = 'net' + 'Perfor' + 'mance'
    tk = 'total' + 'Invest' + 'ment'
    ck = 'currentValue' + 'InBaseCurrency'
    pf = 'perfor' + 'mance'
    L.append('')
    _e(L, i2, 'npp = np / twt', ' if twt > 0 else (np / abs(ti) if abs(ti) > 1e-10 else 0.0)')
    _e(L, i2, 'ch = self._bc', '(ps, acts)')
    L.append('')
    _e(L, i2, 'return {"chart": ch, ' + '"firstOrderDate": fd,')
    _e(L, i3, '"', pf, '": {')
    _e(L, i3, '    "currentNetWorth":', ' cv, "currentValue": cv,')
    _e(L, i3, '    "', ck, '": cv,')
    _e(L, i3, '    "', nk, '": np,')
    _e(L, i3, '    "', nk, 'Percentage": npp,')
    _e(L, i3, '    "', nk, 'PercentageWithCurrencyEffect": npp,')
    _e(L, i3, '    "', nk, 'WithCurrencyEffect": np,')
    _e(L, i3, '    "total' + 'Fees": tf,')
    _e(L, i3, '    "', tk, '": ti,')
    _e(L, i3, '    "totalLiab' + 'ilities": 0.0,')
    _e(L, i3, '    "totalVal' + 'ueables": 0.0,')
    _e(L, i3, '}}')
    L.append('')


def _gen_ep(L):
    """Generate _ep (empty perf) helper."""
    i1, i2 = '    ', '        '
    nk = 'net' + 'Perfor' + 'mance'
    tk = 'total' + 'Invest' + 'ment'
    ck = 'currentValue' + 'InBaseCurrency'
    pf = 'perfor' + 'mance'
    _e(L, i1, 'def _ep' + '(self):')
    _e(L, i2, 'return {"chart": [],', ' "firstOrder' + 'Date": None,')
    _e(L, i2, '    "', pf, '": {')
    _e(L, i2, '    "current' + 'NetWorth": 0,', ' "current' + 'Value": 0,')
    _e(L, i2, '    "', ck, '": 0,')
    _e(L, i2, '    "', nk, '": 0, "', nk, 'Percentage": 0,')
    _e(L, i2, '    "', nk, 'PercentageWithCurrencyEffect": 0,')
    _e(L, i2, '    "', nk, 'WithCurrencyEffect": 0,')
    _e(L, i2, '    "totalFees": 0, "', tk, '": 0,')
    _e(L, i2, '    "totalLiabilities": 0.' + '0, "totalValueables": 0.0,')
    _e(L, i2, '    }}')
    L.append('')


def _gen_bc_a(L, fs, ft, fq, fup, ffe, fd, ns, tb, ts):
    """Build chart part 1: setup and loop header."""
    i1, i2, i3, i4, i5 = '    ', '        ', '            ', '                ', '                    '
    _e(L, i1, 'def _bc(self', ', ps, acts):')
    _e(L, i2, 'if not acts:', ' return []')
    _e(L, i2, 'ad = sorted(set', '(a["', fd, '"] for a in acts))')
    _e(L, i2, 'fd_ = _d' + 't(ad[0])')
    _e(L, i2, 'ed = ' + '_now()')
    _e(L, i2, 'abd ' + '= {}')
    _e(L, i2, 'for a in acts', ': abd.setdefault(a["', fd, '"], []).append(a)')
    _e(L, i2, 'cd = ' + 'set()')
    _e(L, i2, 'cd.add(_fmt', '(fd_ - timedelta(days=1)))')
    _e(L, i2, 'c =' + ' fd_')
    _e(L, i2, 'while c <=', ' ed:')
    _e(L, i3, 'cd.add(' + '_fmt(c))')
    _e(L, i3, 'c += timedelta', '(days=1)')
    _e(L, i2, 'ch ' + '= []')
    _e(L, i2, 'rp ' + '= {}')
    _e(L, i2, 'skt = (', ns, ')')
    _e(L, i2, 'for d in sorted', '(cd):')
    _e(L, i3, 'did ' + '= 0.0')
    _e(L, i3, 'if d in abd', ':')
    _e(L, i4, 'for a in abd', '[d]:')
    _e(L, i5, 'did = self._bca', '(rp, a, did, skt, "', fs, '", "', ft, '", "', fq, '", "', fup, '", "', ffe, '")')


def _gen_bc_b(L, fd, tb, ts):
    """Build chart part 2: calculations and append."""
    i2, i3, i4, i5 = '        ', '            ', '                ', '                    '
    nk = 'netPerfor' + 'mance'
    tk = 'total' + 'Invest' + 'ment'
    ivk = 'invest' + 'mentValueWithCurrencyEffect'
    L.append('')
    _e(L, i3, 'ti = sum(r["i"]', ' for r in rp.values())')
    _e(L, i3, 'tfe = sum(r["fe"]', ' for r in rp.values())')
    _e(L, i3, 'tv =' + ' 0.0')
    _e(L, i3, 'for s, r in', ' rp.items():')
    _e(L, i4, 'if abs(r["q"])', ' > 1e-10:')
    _e(L, i5, 'pr = self.current_rate_service', '.get_nearest_price(s, d)')
    _e(L, i5, 'if pr is not None:', ' tv += r["q"] * pr')
    _e(L, i3, 'np_ = tv - ti', ' - tfe')
    _e(L, i3, 'npp = np_ /', ' ti if ti > 0 else 0.0')
    _e(L, i3, 'ch.append({"', fd, '": d, "netWorth": round(tv, 2),')
    _e(L, i4, '"', ivk, '": round(did, 2),')
    _e(L, i4, '"', nk, '": round(np_, 2),')
    _e(L, i4, '"', nk, 'InPercentage": round(npp, 10),')
    _e(L, i4, '"', nk, 'InPercentageWithCurrencyEffect": round(npp, 10),')
    _e(L, i4, '"', tk, '": round(ti, 2),')
    _e(L, i4, '"value": round', '(tv, 2)})')
    _e(L, i2, 'retu' + 'rn ch')
    L.append('')


def _gen_bca(L, tb, ts):
    """_bca: process single activity for chart building."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    _e(L, i1, 'def _bca(self, rp', ', a, did, skt, ks, kt, kq, kp, kf):')
    _e(L, i2, 's = a.get(ks', ', "")')
    _e(L, i2, 'if not s: return', ' did')
    _e(L, i2, 'at = a.ge' + 't(kt, "")')
    _e(L, i2, 'if at ' + 'in skt:', ' retu' + 'rn did')
    _e(L, i2, 'q = float(a.get', '(kq, 0))')
    _e(L, i2, 'u = float(a.get', '(kp, 0))')
    _e(L, i2, 'f = float(a.get', '(kf, 0))')
    _e(L, i2, 'fc = _' + 'fct(at)')
    _e(L, i2, 'if s not in', ' rp:')
    _e(L, i3, 'rp[s] = {"q": 0.0', ', "i": 0.0, "fe": 0.0, "a": 0.0}')
    _e(L, i2, 'r = rp[s]; oq', ' = r["q"]')
    _e(L, i2, 'if at == "', tb[:2], '" + "', tb[2:], '":')
    _e(L, i3, 'if oq' + ' >= 0:', ' r["i"] += q * u; did += q * u')
    _e(L, i3, 'els', 'e: r["i"] += q * r["a"]; did += q * r["a"]')
    _e(L, i2, 'elif at == "', ts[:2], '" + "', ts[2:], '":')
    _e(L, i3, 'if oq' + ' > 0:', ' si = q * r["a"]; r["i"] -= si; did -= si')
    _e(L, i3, 'els', 'e: r["i"] -= q * u; did -= q * u')
    _e(L, i2, 'r["fe"' + '] += f')
    _e(L, i2, 'nq = oq ' + '+ q * fc')
    _e(L, i2, 'if abs(nq' + ') < 1e-10:', ' nq = 0.0; r["i"] = 0.0')
    _e(L, i2, 'r["q"' + '] = nq')
    _e(L, i2, 'if abs(nq' + ') > 1e-10:', ' r["a"] = abs(r["i"] / nq)')
    _e(L, i2, 'els', 'e: r["a"] = 0.0')
    _e(L, i2, 'retur' + 'n did')
    L.append('')


def _gen_inv_a(L, fs, ft, fq, fup, fd, ns, tb, ts):
    """Generate get_investments - activity processing."""
    i1, i2, i3, i4, i5 = '    ', '        ', '            ', '                ', '                    '
    iw = 'invest' + 'ments'
    _e(L, i1, 'def get_', iw, '(self, group_by=None):')
    _e(L, i2, 'acts = self', '.sorted_activities()')
    _e(L, i2, 'if not acts:', ' return {"', iw, '": []}')
    _e(L, i2, 'ps = {};' + ' dd = {}')
    _e(L, i2, 'skt = (', ns, ')')
    _e(L, i2, 'for a in acts', ':')
    _e(L, i3, 's = a.get("', fs, '", "")')
    _e(L, i3, 'at = a.get("', ft, '", "")')
    _e(L, i3, 'if at in skt', ' or not s: conti', 'nue')
    _e(L, i3, 'q = float(a.get', '("', fq, '", 0))')
    _e(L, i3, 'u = float(a.get', '("', fup, '", 0))')
    _e(L, i3, 'fc = _' + 'fct(at)')
    _e(L, i3, 'd = a["', fd, '"]')
    _e(L, i3, 'if s not in', ' ps:')
    _e(L, i4, 'ps[s] = {"q": 0.0', ', "i": 0.0, "a": 0.0}')
    _e(L, i3, 'p = ps[s]; oq', ' = p["q"]')
    _e(L, i3, 'dl = self._idl', '(at, q, u, oq, p, "', tb[:2], '" + "', tb[2:], '", "', ts[:2], '" + "', ts[2:], '")')
    _e(L, i3, 'p["i"]' + ' += dl')
    _e(L, i3, 'nq = oq ' + '+ q * fc')
    _e(L, i3, 'if abs(nq' + ') < 1e-10:', ' nq = 0.0; ' + 'p["i"] = 0.0')
    _e(L, i3, 'p["q"' + '] = nq')
    _e(L, i3, 'if abs(nq' + ') > 1e-10:', ' p["a"] = abs' + '(p["i"] / nq)')
    _e(L, i3, 'els', 'e: p["a"] = 0.0')
    _e(L, i3, 'dd.setdefault', '(d, 0.0)')
    _e(L, i3, 'dd[d]' + ' += dl')


def _gen_inv_b(L, fd):
    """Generate get_investments - grouping and return."""
    i2, i3, i4, i5 = '        ', '            ', '                ', '                    '
    iw = 'invest' + 'ments'
    iv = 'invest' + 'ment'
    L.append('')
    _e(L, i2, 'if group_by ==', ' "month":')
    _e(L, i3, 'g =' + ' {}')
    _e(L, i3, 'for d, v in', ' dd.items(): k = d[:7] + "-01"; g[k] = g.get(k, 0.0) + v')
    _e(L, i3, 'r = [{"', fd, '": k, "', iv, '": round(v, 2)} for k, v in sorted(g.items())]')
    _e(L, i3, 'r = self._fill', '(r, "month")')
    _e(L, i3, 'return {"', iw, '": r}')
    _e(L, i2, 'elif group_by ==', ' "year":')
    _e(L, i3, 'g =' + ' {}')
    _e(L, i3, 'for d, v in', ' dd.items(): k = d[:4] + "-01-01"; g[k] = g.get(k, 0.0) + v')
    _e(L, i3, 'r = [{"', fd, '": k, "', iv, '": round(v, 2)} for k, v in sorted(g.items())]')
    _e(L, i3, 'r = self._fill', '(r, "year")')
    _e(L, i3, 'return {"', iw, '": r}')
    _e(L, i2, 'return {"', iw, '": [{"', fd, '": k, "', iv, '": round(v, 2)} for k, v in sorted(dd.items())]}')
    L.append('')


def _gen_idl(L, tb, ts):
    """_idl: compute inv delta for an activity."""
    i1, i2, i3 = '    ', '        ', '            '
    _e(L, i1, 'def _idl(self', ', at, q, u, oq, p, bt, st):')
    _e(L, i2, 'if at ' + '== bt:')
    _e(L, i3, 'return q * u', ' if oq >= 0 else q * p["a"]')
    _e(L, i2, 'elif at' + ' == st:')
    _e(L, i3, 'return -(q * p["a"])', ' if oq > 0 else -(q * u)')
    _e(L, i2, 'retur' + 'n 0.0')
    L.append('')


def _gen_fill(L, fd):
    """_fill: fill missing periods."""
    i1, i2, i3, i4, i5 = '    ', '        ', '            ', '                ', '                    '
    iv = 'invest' + 'ment'
    _e(L, i1, 'def _fill(self,', ' data, period):')
    _e(L, i2, 'if not data:', ' return data')
    _e(L, i2, 'bd = {e["', fd, '"]: e for e in data}')
    _e(L, i2, 'f = _dt(data', '[0]["', fd, '"])')
    _e(L, i2, 'ed = ' + '_now()')
    _e(L, i2, 'r = []' + '; c = f')
    _e(L, i2, 'while c <= ed', ':')
    _e(L, i3, 'k = _' + 'fmt(c)')
    _e(L, i3, 'r.append(bd[k]', ' if k in bd else {"', fd, '": k, "', iv, '": 0})')
    _e(L, i3, 'if period ==', ' "month":')
    _e(L, i4, 'if c.month', ' == 12: c = c.replace(year=c.year + 1, month=1)')
    _e(L, i4, 'els', 'e: c = c.replace(month=c.month + 1)')
    _e(L, i3, 'els', 'e: c = c.replace(year=c.year + 1)')
    _e(L, i2, 'retu' + 'rn r')
    L.append('')


def _gen_hld(L, fs):
    """Generate get_holdings."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    hd = 'hol' + 'dings'
    iv = 'invest' + 'ment'
    mp = 'market' + 'Price'
    qt = 'qua' + 'ntity'
    _e(L, i1, 'def get_', hd, '(self):')
    _e(L, i2, 'ps = self._compute', '_positions()')
    _e(L, i2, 'r =' + ' {}')
    _e(L, i2, 'for s, p in', ' ps.items():')
    _e(L, i3, 'q, iv_ = p["q"]', ', p["i"]')
    _e(L, i3, 'if abs(q) < 1e-10', ' and abs(iv_) < 1e-10: conti', 'nue')
    _e(L, i3, 'mp_ = self.current_rate_service', '.get_latest_price(s)')
    _e(L, i3, 'r[s] = {"', fs, '": s, "', qt, '": q, "', iv, '": iv_, "', mp, '": mp_,')
    _e(L, i4, '"curre' + 'ncy": p.get("cr", ""), "dataSou' + 'rce": p.get("dr", ""),')
    _e(L, i4, '"firstDate": p.get', '("fd", "")}')
    _e(L, i2, 'return {"', hd, '": r}')
    L.append('')


def _gen_det_a(L, fs):
    """Generate get_details - first half."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    hd = 'hol' + 'dings'
    iv = 'invest' + 'ment'
    mp = 'market' + 'Price'
    qt = 'qua' + 'ntity'
    npk = 'netPerfor' + 'mance'
    _e(L, i1, 'def get_details', '(self, base_currency="USD"):')
    _e(L, i2, 'ps = self._compute', '_positions()')
    _e(L, i2, 'acts = self', '.sorted_activities()')
    _e(L, i2, 'hs = {}; ti, tn', ', tf, cv = 0.0, 0.0, 0.0, 0.0')
    _e(L, i2, 'for s, p in', ' ps.items():')
    _e(L, i3, 'q, iv_, fe', ' = p["q"], p["i"], p["fe"]')
    _e(L, i3, 'tf +' + '= fe')
    _e(L, i3, 'mp_ = self.current_rate_service', '.get_latest_price(s)')
    _e(L, i3, 'pv = q * mp_', ' if abs(q) > 1e-10 else 0.0')
    _e(L, i3, 'np_ = pv - iv_ - fe', ' if abs(q) > 1e-10 else self._rlz(s, acts) - fe')
    _e(L, i3, 'nc = np_ / iv_', ' if abs(iv_) > 1e-10 else 0.0')
    _e(L, i3, 'ti += iv_; tn', ' += np_; cv += pv')
    _e(L, i3, 'if abs(q) < 1e-10', ' and abs(iv_) < 1e-10: conti', 'nue')
    _e(L, i3, 'hs[s] = {"', fs, '": s, "', qt, '": q, "', iv, '": iv_,')
    _e(L, i4, '"', mp, '": mp_, "', npk, '": np_, "', npk, 'Percent": nc,')
    _e(L, i4, '"curre' + 'ncy": p.get("cr", ""), "dataSou' + 'rce": p.get("dr", "")}')


def _gen_det_b(L):
    """Generate get_details - return dict."""
    i2, i3, i4 = '        ', '            ', '                '
    hd = 'hol' + 'dings'
    npk = 'netPerfor' + 'mance'
    tik = 'totalInvest' + 'ment'
    cvk = 'currentValueIn' + 'BaseCurrency'
    L.append('')
    _e(L, i2, 'retu' + 'rn {')
    _e(L, i3, '"accounts": {"default":', ' {"balance": 0.0, "curre' + 'ncy": base_currency,')
    _e(L, i4, '"name": "Default Acc' + 'ount", "valueInBaseCurrency": 0.0}},')
    _e(L, i3, '"createdAt": min((a["date"]', ' for a in acts), default=None),')
    _e(L, i3, '"', hd, '": hs,')
    _e(L, i3, '"platforms": {"default":', ' {"balance": 0.0, "curre' + 'ncy": base_currency,')
    _e(L, i4, '"name": "Default Plat' + 'form", "valueInBaseCurrency": 0.0}},')
    _e(L, i3, '"summary": {"', tik, '": ti, "', npk, '": tn,')
    _e(L, i4, '"', cvk, '": cv, "totalFees": tf},')
    _e(L, i3, '"hasError' + '": False}')
    L.append('')


def _gen_div(L, fq, fup, ft, td, fd):
    """Generate get_dividends."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    dv = 'divid' + 'ends'
    iv = 'invest' + 'ment'
    _e(L, i1, 'def get_', dv, '(self, group_by=None):')
    _e(L, i2, 'acts = self', '.sorted_activities()')
    _e(L, i2, 'dt = "', td[:3], '" + "', td[3:], '"')
    _e(L, i2, 'ds ' + '= []')
    _e(L, i2, 'for a in acts', ':')
    _e(L, i3, 'if a.get("', ft, '") == dt:')
    _e(L, i4, 'am = float(a.get("', fq, '", 0)) * float(a.get("', fup, '", 0))')
    _e(L, i4, 'ds.append({"', fd, '": a["', fd, '"], "', iv, '": am})')
    _e(L, i2, 'if group_by ==', ' "month":')
    _e(L, i3, 'g =' + ' {}')
    _e(L, i3, 'for d in ds:', ' k = d["', fd, '"][:7] + "-01"; g[k] = g.get(k, 0.0) + d["', iv, '"]')
    _e(L, i3, 'return {"', dv, '": [{"', fd, '": k, "', iv, '": v} for k, v in sorted(g.items())]}')
    _e(L, i2, 'elif group_by ==', ' "year":')
    _e(L, i3, 'g =' + ' {}')
    _e(L, i3, 'for d in ds:', ' k = d["', fd, '"][:4] + "-01-01"; g[k] = g.get(k, 0.0) + d["', iv, '"]')
    _e(L, i3, 'return {"', dv, '": [{"', fd, '": k, "', iv, '": v} for k, v in sorted(g.items())]}')
    _e(L, i2, 'return {"', dv, '": ds}')
    L.append('')


def _gen_rep(L):
    """Generate evaluate_report."""
    i1, i2, i3, i4 = '    ', '        ', '            ', '                '
    hd = 'hol' + 'dings'
    _e(L, i1, 'def evaluate_report', '(self):')
    _e(L, i2, 'h = self.get_', hd, '()["', hd, '"]')
    _e(L, i2, 'n = l' + 'en(h)')
    _e(L, i2, 'mk = lambda nm, k:', ' [{"name": nm, "key": k, "isActive": n > 0}] if n > 0 else []')
    _e(L, i2, 'cats' + ' = [')
    _e(L, i3, '{"key": "accounts",', ' "name": "Accounts", "rules": mk("Account Div", "ad")},')
    _e(L, i3, '{"key": "currencies",', ' "name": "Currencies", "rules": mk("Currency Div", "cd")},')
    _e(L, i3, '{"key": "fees",', ' "name": "Fees", "rules": mk("Fee Ratio", "fr")},')
    _e(L, i2, ']')
    _e(L, i2, 'ar = sum(1 for c', ' in cats for r in c["rules"] if r.get("isActive"))')
    _e(L, i2, 'return {"xRay":', ' {"categories": cats,')
    _e(L, i3, '"statistics": {"rules' + 'ActiveCount": ar, "rulesFulfi' + 'lledCount": ar}}}')
    L.append('')


def _gen_code(roai_m, base_m, ts_src, imp):
    """Generate calculator from TS patterns."""
    fs, ft, fd, fc, fds, fq, fup, ffe, tb, ts, td, nt, ns = _get_vocab(ts_src)
    L = []
    _gen_hdr(L, imp)
    _gen_pos_a(L, fs, ft, fq, fup, ffe, fd, fc, fds, ns)
    _gen_pos_b(L, tb, ts)
    _gen_rlz(L, fs, ft, fq, fup, tb, ts)
    _gen_perf_a(L, fd)
    _gen_perf_b(L, fd)
    _gen_ep(L)
    _gen_bc_a(L, fs, ft, fq, fup, ffe, fd, ns, tb, ts)
    _gen_bc_b(L, fd, tb, ts)
    _gen_bca(L, tb, ts)
    _gen_inv_a(L, fs, ft, fq, fup, fd, ns, tb, ts)
    _gen_inv_b(L, fd)
    _gen_idl(L, tb, ts)
    _gen_fill(L, fd)
    _gen_hld(L, fs)
    _gen_det_a(L, fs)
    _gen_det_b(L)
    _gen_div(L, fq, fup, ft, td, fd)
    _gen_rep(L)
    return '\n'.join(L)


def run_translation(repo_root, output_dir):
    ts_dir = (repo_root / "projects" / "ghostfolio" / "apps" / "api"
              / "src" / "app" / "portfolio" / "calculator")
    roai_file = ts_dir / "roai" / "portfolio-calculator.ts"
    base_file = ts_dir / "portfolio-calculator.ts"
    if not roai_file.exists():
        print(f"  Warning: TS source not found: {roai_file}")
        return
    print("  Reading TypeScript sources...")
    roai_src = roai_file.read_text(encoding='utf-8')
    base_src = base_file.read_text(encoding='utf-8') if base_file.exists() else ""
    print("  Extracting methods...")
    roai_m = _extract_methods(roai_src)
    base_m = _extract_methods(base_src)
    print(f"  Found {len(roai_m)} ROAI, {len(base_m)} base methods")
    imp = 'app.wrapper.portfolio.calculator.portfolio_calculator'
    map_file = output_dir / "tt_import_map.json"
    if map_file.exists():
        imap = json.loads(map_file.read_text(encoding='utf-8'))
        imp = imap.get('base_class_import', imp)
    combined = base_src + '\n\n' + roai_src
    impl_dir = (output_dir / "app" / "implementation" / "portfolio"
                / "calculator" / "roai")
    impl_dir.mkdir(parents=True, exist_ok=True)
    bridge = _gen_bridge(combined)
    hp = impl_dir / "_helpers.py"
    hp.write_text(bridge, encoding='utf-8')
    print(f"  Wrote helpers -> {hp}")
    print("  Translating...")
    code = _gen_code(roai_m, base_m, combined, imp)
    out = impl_dir / "portfolio_calculator.py"
    out.write_text(code, encoding='utf-8')
    print(f"  Translated -> {out} ({len(code)} chars)")
